### ISSUE TITLE
Broken link to pretrained models

### ISSUE THREAD

**Issue by mbarnig** [keonlee9420/Comprehensive-Tacotron2#1]
The link [https://github.com/keonlee9420/Comprehensive-Tacotron2/blob/main](https://github.com/keonlee9420/Comprehensive-Tacotron2/blob/main) indicated in the Readme shows a page not found 404.

**Comment by keonlee9420** [comment]
Hi @mbarnig , thank you for the attention and yes it is not working since I did not link the model yet. It's being trained and i'll share after that.

**Comment by keonlee9420** [comment]
@mbarnig now you can check the LJSpeech model and audio demo. VCTK will be updated later since it's multi-speaker and the model needs more steps to train.

**Comment by mbarnig** [comment]
Great. Thank you very much.
