### ISSUE TITLE
some questions about synthesize

### ISSUE THREAD

**Issue by guoaoo** [keonlee9420/Comprehensive-Tacotron2#3]
@keonlee9420 Thanks for your great work of this repo!

However, I have some questions about this model:
1. I have used the pretrained model to get good performance on single speaker (LJSpeech), but can't synthesize speech on multi-speaker, becasue I dont have the speaker embedding on VCTK. **Could you upload some speaker embedding .npy files such as the default speaker "p225" ?** I am downloading VCTK but expect it to take a day.
2. Have you tested the performance on the LibriTTS dataset?

**Comment by keonlee9420** [comment]
Hi @guoaoo , thank you for your attention. To answer your questions,
1. As you already know, you can extract the speaker embedding .npy files through the processing as described in README.md. But I also share it [here](https://drive.google.com/drive/folders/1a4YW2UWdlF9RTqG_phv_VbRjyEcAld7t?usp=sharing) for your convenience. Please download/unzip the zip file and put them in `preprocessed_data/VCTK/spker_embed`.
2. I haven't tried yet, but it should work as well. You can preprocess LibriTTS following VCTK as a multi-speaker dataset.

Hope this helps!

**Comment by guoaoo** [comment]
Thank you for such a quick reply!
I'm sorry because I saw the message last night but didn't get to do the test in time, now I'll try

**Comment by guoaoo** [comment]
Hi @keonlee9420 , I'm new to audio signals, so I have some questions about

https://github.com/keonlee9420/Comprehensive-Tacotron2/blob/4746fccdfc521b878ca522f675457f0de6b69644/config/VCTK/preprocess.yaml#L20-L21

1. skip_len=14848 means we will skip audio shorter than 14848/22050≈0.67s? Why do you choice 14848?
2. Why do you choice 23 as trim_top_db in VCTK and LJSpeech. The default top_db in librosa is 60. 

I'm sorry to bother you and looking forward to your reply! 😉

**Comment by keonlee9420** [comment]
Hi @guoaoo , sorry for TOO late response.. I followed [here](https://github.com/Yeongtae/tacotron2/blob/eee187d61fbb897828fd8d964e34c55db9c53502/skip_short_clip.py#L19) for `skip_len` and [here](https://github.com/Yeongtae/tacotron2/blob/eee187d61fbb897828fd8d964e34c55db9c53502/preprocess_audio.py#L10) for `trim_top_db`, and they totally depend on the dataset.

**Comment by guoaoo** [comment]
Thank you. @keonlee9420
